param(
    [string]$InputInstaller,
    [string]$OutputInstaller,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$toolRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $toolRoot "..\..")
$releaseDir = Join-Path $repoRoot "release"

if (!$InputInstaller) {
    $InputInstaller = Join-Path $releaseDir "ErireCore-FirstStand-Setup.exe"
}
if (!$OutputInstaller) {
    $OutputInstaller = Join-Path $repoRoot "app\static\downloads\ErireInstaller.exe"
}

$inputItem = Get-Item -LiteralPath $InputInstaller
$cabPath = Join-Path $releaseDir "ErireInstaller-payload.cab"
$ddfPath = Join-Path $releaseDir "ErireInstaller-payload.ddf"
$rptPath = Join-Path $releaseDir "ErireInstaller-payload.rpt"
$layoutPath = Join-Path $releaseDir "ErireInstaller-payload-layout.inf"
$makecabLog = Join-Path $releaseDir "ErireInstaller-payload.makecab.log"
$stubPath = Join-Path $releaseDir "ErireInstaller-sfx-stub.exe"
$releaseSfx = Join-Path $releaseDir "ErireInstaller-compressed.exe"
$launcherSource = Join-Path $toolRoot "src\compressed_launcher.c"
$launcherIcon = Join-Path $repoRoot "assets\brand\erire-logo.ico"
$launcherRc = Join-Path $releaseDir "ErireInstaller-sfx-stub.rc"
$launcherRes = Join-Path $releaseDir "ErireInstaller-sfx-stub-res.o"

function To-MsysPath([string]$path) {
    if (Test-Path -LiteralPath $path) {
        $resolved = (Resolve-Path -LiteralPath $path).Path
    } else {
        $parent = Split-Path -Parent $path
        $leaf = Split-Path -Leaf $path
        $resolved = Join-Path (Resolve-Path -LiteralPath $parent).Path $leaf
    }
    $resolved = $resolved -replace '\\','/'
    if ($resolved -match '^([A-Za-z]):/(.*)$') {
        return "/" + $Matches[1].ToLowerInvariant() + "/" + $Matches[2]
    }
    return $resolved
}

function Invoke-Bash([string]$command) {
    $bash = if ($env:MSYS_BASH) { $env:MSYS_BASH } else { "C:\msys64\usr\bin\bash.exe" }
    if (!(Test-Path -LiteralPath $bash)) {
        throw "MSYS bash not found at $bash"
    }
    & $bash -lc $command
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed: $command"
    }
}

function Write-UInt64([System.IO.BinaryWriter]$writer, [UInt64]$value) {
    $writer.Write($value)
}

New-Item -ItemType Directory -Force -Path $releaseDir | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputInstaller) | Out-Null

$needsCab = $Force -or !(Test-Path -LiteralPath $cabPath) -or ((Get-Item -LiteralPath $cabPath).LastWriteTime -lt $inputItem.LastWriteTime)
if ($needsCab) {
    $sourceDir = Split-Path -Parent $inputItem.FullName
    $sourceName = $inputItem.Name
    @"
; Auto-generated by compress_download_installer.ps1.
.Set CabinetNameTemplate=$cabPath
.Set CompressionType=LZX
.Set CompressionLevel=7
.Set CompressionMemory=21
.Set InfFileName=$layoutPath
.Set RptFileName=$rptPath
.Set MaxDiskSize=CDROM
.Set ReservePerCabinetSize=0
.Set InfCabinetLineFormat=*cab#*=Application Source Media,*cabfile*,0
.Set Compress=on
.Set DiskDirectoryTemplate=
.Set Cabinet=ON
.Set MaxCabinetSize=999999999
.Set InfDiskHeader=
.Set InfDiskLineFormat=
.Set InfCabinetHeader=[SourceDisksNames]
.Set InfFileHeader=
.Set InfFileHeader1=[SourceDisksFiles]
.Set InfFileLineFormat=*file*=*cab#*,,*size*,*csum*
"$($inputItem.FullName)"
"@ | Set-Content -LiteralPath $ddfPath -Encoding ASCII

    if (Test-Path -LiteralPath $cabPath) {
        Remove-Item -LiteralPath $cabPath -Force
    }
    & makecab.exe /F $ddfPath *> $makecabLog
    if ($LASTEXITCODE -ne 0) {
        throw "makecab failed. See $makecabLog"
    }
}

$needsStub = $Force -or !(Test-Path -LiteralPath $stubPath) -or ((Get-Item -LiteralPath $stubPath).LastWriteTime -lt (Get-Item -LiteralPath $launcherSource).LastWriteTime)
if (!$needsStub -and (Test-Path -LiteralPath $launcherIcon)) {
    $needsStub = (Get-Item -LiteralPath $stubPath).LastWriteTime -lt (Get-Item -LiteralPath $launcherIcon).LastWriteTime
}
if ($needsStub) {
    $repoMsys = To-MsysPath $repoRoot
    $sizeFlags = "-Os -ffunction-sections -fdata-sections -Wl,--gc-sections -s"
    if (Test-Path -LiteralPath $launcherIcon) {
        $iconPath = (Resolve-Path -LiteralPath $launcherIcon).Path.Replace("\", "\\")
        "1 ICON `"$iconPath`"" | Set-Content -LiteralPath $launcherRc -Encoding ASCII
        Invoke-Bash "export PATH=/ucrt64/bin:/usr/bin:`$PATH; cd '$repoMsys' && windres -i '$(To-MsysPath $launcherRc)' -O coff -o '$(To-MsysPath $launcherRes)' && gcc -std=c11 $sizeFlags -Wall -Wextra -Wno-format-truncation -mwindows -o '$(To-MsysPath $stubPath)' '$(To-MsysPath $launcherSource)' '$(To-MsysPath $launcherRes)' -luser32 -lshell32"
    } else {
        Invoke-Bash "export PATH=/ucrt64/bin:/usr/bin:`$PATH; cd '$repoMsys' && gcc -std=c11 $sizeFlags -Wall -Wextra -Wno-format-truncation -mwindows -o '$(To-MsysPath $stubPath)' '$(To-MsysPath $launcherSource)' -luser32 -lshell32"
    }
}

Copy-Item -LiteralPath $stubPath -Destination $releaseSfx -Force

$outStream = [System.IO.File]::Open($releaseSfx, [System.IO.FileMode]::Append, [System.IO.FileAccess]::Write, [System.IO.FileShare]::None)
try {
    $cabOffset = [UInt64]$outStream.Position
    $cabStream = [System.IO.File]::OpenRead($cabPath)
    try {
        $cabSize = [UInt64]$cabStream.Length
        $cabStream.CopyTo($outStream)
    } finally {
        $cabStream.Dispose()
    }

    $writer = [System.IO.BinaryWriter]::new($outStream, [System.Text.Encoding]::ASCII, $true)
    try {
        $magic = New-Object byte[] 16
        [System.Text.Encoding]::ASCII.GetBytes("ERIRECAB1").CopyTo($magic, 0)
        $writer.Write($magic)
        Write-UInt64 $writer $cabOffset
        Write-UInt64 $writer $cabSize
    } finally {
        $writer.Dispose()
    }
} finally {
    $outStream.Dispose()
}

Copy-Item -LiteralPath $releaseSfx -Destination $OutputInstaller -Force

$compressedItem = Get-Item -LiteralPath $OutputInstaller
$ratio = [math]::Round(($compressedItem.Length / $inputItem.Length) * 100, 2)
Write-Host "Compressed installer created:"
Write-Host "Input:  $($inputItem.FullName) ($([math]::Round($inputItem.Length / 1MB, 2)) MB)"
Write-Host "Output: $($compressedItem.FullName) ($([math]::Round($compressedItem.Length / 1MB, 2)) MB, $ratio%)"
Write-Host "Release copy: $releaseSfx"
